//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : main.java
//  @ Date : 12/08/2026
//  @ Author : 
//
//


import java.util.Scanner;

public class main {
	private static Usuario usuarioActivo;
	private static Scanner teclado = new Scanner(System.in);
	public static void main(String[] args) {
		opcionNuevoUsuario();
		int opcion = 0;
		while (opcion != 9){
			mostrarMenu();
			System.out.println("Ingrese una opcion: ");
			opcion = teclado.nextInt();
			teclado.nextLine();

			switch (opcion) {
				case 1:
					opcionNuevoUsuario();
					break;
				case 2:
					opcionRegistrarCalificacion();
					break;
				case 3: 
					opcionConsultarCalificaciones();
					break;
				case 4: opcionConsultarPelicula();
					break;
				case 5:
					opcionModificarCalificacion();
					break;
				case 6: 
					opcionMostrarPromedio();
					break;
				case 7: 
					opcionMejorPeorCalificacion();
					break;
				case 8: 
					opcionEspaciosDisponibles();
					break;
				case 9:
					System.out.println("Saliendo del programa");
					break;
				default: 
					System.out.println("Invalido");
					break;
				
			}
		}			
	}

	private static void mostrarMenu() {
		System.out.println();
		System.out.println("MENU");
		System.out.println("1. Nuevo Usuario");
		System.out.println("2. Registrar nueva calificacion");
		System.out.println("3. Consultar calificaciones");
		System.out.println("4. Consultar una pelicula");
		System.out.println("5. Modificar calificacion");
		System.out.println("6. Mostrar promedio");
		System.out.println("7. Mostrar mejor y peor calificacion");
		System.out.println("8. Consultar espacios disponibles");
		System.out.println("9. Salir");
	}	
	
	private static void opcionNuevoUsuario() {

  System.out.println("Ingrese su nombre: ");
    String nombre = teclado.nextLine();

    System.out.println("Ingrese su nombre de usuario: ");
    String nombreUsuario = teclado.nextLine();

    System.out.println("Ingrese su edad: ");
    int edad = teclado.nextInt();
    teclado.nextLine();

    usuarioActivo = new Usuario(nombre, nombreUsuario, edad);

    System.out.println("Usuario creado correctamente");
}
	
	private static void opcionRegistrarCalificacion() {
		System.out.println("Ingrese la calificacion de la pelicula (1-10): ");
		int calificacion = teclado.nextInt();
		teclado.nextLine();

		boolean registrado = usuarioActivo.registrarCalificacion(calificacion);

		if(registrado){
			System.out.println("Calificacion registrada correctamente");
			
		}
		else{
			System.out.println("No se registro la calificacion");
		}
		
	}
	
	private static void opcionConsultarCalificaciones() {
	}
	
	private static void opcionConsultarPelicula() {
	}
	
	private static void opcionModificarCalificacion() {System.out.println("Ingrese el numero de pelicula: ");
        int numeroPelicula = teclado.nextInt();

        System.out.println("Ingrese la nueva calificacion (1-10): ");
        int nuevaCalificacion = teclado.nextInt();
        teclado.nextLine();

        boolean modificado =
                usuarioActivo.modificarCalificacion(
                    numeroPelicula,
                    nuevaCalificacion
                );

        if (modificado) {

            System.out.println(
                "Calificacion modificada correctamente"
            );

        } else {

            System.out.println(
                "No se pudo modificar la calificacion"
            );
        }
    }

    private static void opcionMostrarPromedio() {

        if (usuarioActivo.obtenerCantidadRegistradas() == 0) {

            System.out.println(
                "No hay calificaciones registradas"
            );

        } else {

            double promedio =
                    usuarioActivo.calcularPromedio();

            System.out.println(
                "Promedio de calificaciones: " + promedio
            );
        }
    }

    private static void opcionMejorPeorCalificacion() {

        if (usuarioActivo.obtenerCantidadRegistradas() == 0) {

            System.out.println(
                "No hay calificaciones registradas"
            );

        } else {

            int mejor =
                    usuarioActivo.obtenerCalificacionMasAlta();

            int peor =
                    usuarioActivo.obtenerCalificacionMasBaja();

            System.out.println(
                "Mejor calificacion: " + mejor
            );

            System.out.println(
                "Peor calificacion: " + peor
            );
        }
    }

    private static void opcionEspaciosDisponibles() {

        int registradas =
                usuarioActivo.obtenerCantidadRegistradas();

        int disponibles =
                usuarioActivo.obtenerEspaciosDisponibles();

        System.out.println(
            "Peliculas calificadas: " + registradas
        );

        System.out.println(
            "Espacios disponibles: " + disponibles
        );
    }
}