//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pelicula.java
//  @ Date : 12/08/2026
//  @ Author : 
//
//




public class Pelicula {
	private int calificacion;
	public Pelicula(int calificacion) {
		this.calificacion = calificacion;
	}
	
	public int getCalificacion() {
		return calificacion;
	}
	
	public void setCalificacion(int calificacion) {
		this.calificacion = calificacion;
	}
	
	public String toString() {
		return "Calificación: " + calificacion;
	}
}
