//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Caso.java
//  @ Date : 02/09/2026
//  @ Author : 
//
//


import java.util.ArrayList;

public class Caso {
	private Ubicacion[] ubicaciones;
	private ArrayList<Pista> pistas;
	private String nombreCaso;
	private String codigoIdentificacion;
	private String detectiveResponsable;
	public Caso(String nombreCaso, String codigoIdentificacion, String detectiveResponsable) {
		this.nombreCaso = nombreCaso;
		this.codigoIdentificacion = codigoIdentificacion;
		this.detectiveResponsable = detectiveResponsable;
		ubicaciones = new Ubicacion[5];
		pistas = new ArrayList<>();
	}
	
	public void registrarUbicacion(int posicion, Ubicacion u) {
	if (u == null){
		throw new IllegalArgumentException("La ubicacion no existe/valida");
	}
	if (posicion < 0 || posicion >= ubicaciones.length){
		throw new IndexOutOfBoundsException( "La posicion debe estar entre 0 y " + (ubicaciones.length - 1));
		}
	if (ubicaciones[posicion] != null){
		throw new IllegalStateException("La posicion ya está ocupada");
	}
	ubicaciones[posicion] = u;
	}
	
	public void consultarUbicaciones() {
		for (int i = 0; i < ubicaciones.length; i++) {
			if (ubicaciones[i] != null) {
				System.out.println("Posicion:" + i);
				System.out.println(ubicaciones[i]);
				
			}
		}
	}
	
	public Ubicacion consultarUbicacion(int posicion) {
		if (posicion < 0 || posicion >= ubicaciones.length){
			throw new IndexOutOfBoundsException("Posición Invalida");
		}
		if (ubicaciones[posicion] == null) {
			throw new IllegalStateException("La posicion esta vacia");
			
		}
		return ubicaciones[posicion];
	}
	
	public void modificarUbicacion(int posicion, int nuevoRiesgo, String nuevoEstado) {
		Ubicacion ubicacion = consultarUbicacion(posicion);
		ubicacion.setNivelRiesgo(nuevoRiesgo);
		ubicacion.setEstado(nuevoEstado);

	}
	
	public void descartarUbicacion(int posicion) {
		consultarUbicacion(posicion);
		ubicaciones[posicion] = null;
	}
	
	public void registrarPista(Pista p) {
		if (p == null){
			throw new IllegalArgumentException("La pista no es valida/existe");
		}
		if (buscarPista(p.getCodigo()) != null){
			throw new  IllegalArgumentException("Ya existe una pista con ese código.");
		}
		pistas.add(p);
	}
	
	public void consultarPistas() {
		if (pistas.isEmpty()){
			System.out.println("No hay pistas registradas.");
			return ;
		}
		for (Pista pista: pistas){
			System.out.println(pista);
		}
	}
	
	public Pista buscarPista(String codigo) {
		for (Pista pista : pistas){
			if (pista.getCodigo().equals(codigo)) {
				return pista;
				
			}
		}
		return null;
	}
	
	public void modificarPista(String codigo, String nuevaDescripcion, String nuevoTipo, int nuevaImportancia, int nuevaConfiabilidad) {
		Pista pista = buscarPista(codigo);
		if (pista == null){
			throw new IllegalStateException("No existe una pista con el código");
		}
		pista.setDescripcion(nuevaDescripcion);
		pista.setTipoEvidencia(nuevoTipo);
		pista.setNivelImportancia(nuevaImportancia);
		pista.setNivelConfiabilidad(nuevaConfiabilidad);
	}
	
	public void eliminarPista(String codigo) {
		Pista pista = buscarPista(codigo);
		if (pista == null){
			throw new IllegalStateException(
				"No existe una pista con ese código");
		}
		pistas.remove(pista);
	}
	
	public int getCantidadUbicacionesRegistradas() {
		int cantidad = 0;
		
		for (Ubicacion ubicacion : ubicaciones){
			if(ubicacion != null){
				cantidad++;
			}
		}
		return cantidad;
	}
	
	public int getEspaciosDisponibles() {
		return ubicaciones.length - getCantidadUbicacionesRegistradas();
	}
	
	public Ubicacion getUbicacionMayorRiesgo() {
		Ubicacion mayor = null;
		for (Ubicacion ubicacion : ubicaciones){
			if (ubicacion != null){
				if (mayor == null || ubicacion.getNivelRiesgo() > mayor.getNivelRiesgo()){
					mayor = ubicacion;
				}
			}
		}
		return mayor;
	}
	
	public int getCantidadPistas() {
		return pistas.size();

	}
	
	public Pista getPistaMayorImportancia() {
		Pista mayor = null;
		for (Pista pista : pistas){
			if (pista != null){
				if (mayor == null || pista.getNivelImportancia() > mayor.getNivelImportancia());
				mayor = pista;
			}
		}
		return mayor;
	}
	
	public Pista getPistaMayorConfiabilidad() {
		Pista mayor = null;
		for (Pista pista : pistas){
			if (pista != null){
				if (mayor == null || pista.getNivelConfiabilidad() > mayor.getNivelConfiabilidad()){
				mayor = pista;
				}
			}
		}
		return mayor;
	}
	
	public double getPromedioImportancia() {
		if (pistas.isEmpty()){
			return 0.0;
		}
		double suma = 0;

		for (Pista pista: pistas){
			suma += pista.getNivelImportancia();

		}
	return suma / pistas.size();
	}
}
