//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : main.java
//  @ Date : 02/09/2026
//  @ Author : 
//
import java.util.Scanner;

public class main {
    private static Caso casoActivo;
    private static Scanner teclado = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("=== CIA ===");

        System.out.print("Nombre del caso: ");
        String nombreCaso = teclado.nextLine();

        System.out.print("Código de identificación: ");
        String codigoIdentificacion = teclado.nextLine();

        System.out.print("Detective al mando: ");
        String detectiveResponsable = teclado.nextLine();

        casoActivo = new Caso(
            nombreCaso,
            codigoIdentificacion,
            detectiveResponsable
        );

        int opcion = 0;

        while (opcion != 13) {
            try {
                mostrarMenu();

                opcion = teclado.nextInt();
                teclado.nextLine();

                switch (opcion) {
                    case 1: {
                        System.out.print("Nombre del nuevo caso: ");
                        String nombre = teclado.nextLine();

                        System.out.print("Código de identificación: ");
                        String codigo = teclado.nextLine();

                        System.out.print("Detective responsable: ");
                        String detective = teclado.nextLine();

                        casoActivo = new Caso(nombre, codigo, detective);

                        System.out.println("Nuevo caso creado.");
                        break;
                    }

                    case 2: {
                        System.out.print("Posición del arreglo (0-4): ");
                        int posicion = teclado.nextInt();
                        teclado.nextLine();

                        System.out.print("Código de la ubicación: ");
                        String codigo = teclado.nextLine();

                        System.out.print("Nombre de la ubicación: ");
                        String nombre = teclado.nextLine();

                        System.out.print("Dirección: ");
                        String direccion = teclado.nextLine();

                        System.out.print("Nivel de riesgo (1-10): ");
                        int riesgo = teclado.nextInt();
                        teclado.nextLine();

                        System.out.print("Estado: ");
                        String estado = teclado.nextLine();

                        Ubicacion ubicacion = new Ubicacion(
                            codigo,
                            nombre,
                            direccion,
                            riesgo,
                            estado
                        );

                        casoActivo.registrarUbicacion(posicion, ubicacion);

                        System.out.println("Ubicación registrada.");
                        break;
                    }

                    case 3: {
                        casoActivo.consultarUbicaciones();
                        break;
                    }

                    case 4: {
                        System.out.print("Posición que desea consultar: ");
                        int posicion = teclado.nextInt();
                        teclado.nextLine();

                        Ubicacion ubicacion =
                            casoActivo.consultarUbicacion(posicion);

                        System.out.println(ubicacion);
                        break;
                    }

                    case 5: {
                        System.out.print("Posición que desea modificar: ");
                        int posicion = teclado.nextInt();
                        teclado.nextLine();

                        System.out.print("Nuevo nivel de riesgo (1-10): ");
                        int riesgo = teclado.nextInt();
                        teclado.nextLine();

                        System.out.print("Nuevo estado: ");
                        String estado = teclado.nextLine();

                        casoActivo.modificarUbicacion(
                            posicion,
                            riesgo,
                            estado
                        );

                        System.out.println("Ubicación modificada.");
                        break;
                    }

                    case 6: {
                        System.out.print("Posición que desea descartar: ");
                        int posicion = teclado.nextInt();
                        teclado.nextLine();

                        casoActivo.descartarUbicacion(posicion);

                        System.out.println("Ubicación descartada.");
                        break;
                    }

                    case 7: {
                        System.out.print("Código de la pista: ");
                        String codigo = teclado.nextLine();

                        System.out.print("Descripción: ");
                        String descripcion = teclado.nextLine();

                        System.out.print("Tipo de evidencia: ");
                        String tipo = teclado.nextLine();

                        System.out.print("Nivel de importancia (1-10): ");
                        int importancia = teclado.nextInt();
                        teclado.nextLine();

                        System.out.print("Nivel de confiabilidad (0-100): ");
                        int confiabilidad = teclado.nextInt();
                        teclado.nextLine();

                        Pista pista = new Pista(
                            codigo,
                            descripcion,
                            tipo,
                            importancia,
                            confiabilidad
                        );

                        casoActivo.registrarPista(pista);

                        System.out.println("Pista registrada.");
                        break;
                    }

                    case 8: {
                        casoActivo.consultarPistas();
                        break;
                    }

                    case 9: {
                        System.out.print("Código de la pista: ");
                        String codigo = teclado.nextLine();

                        Pista pista = casoActivo.buscarPista(codigo);

                        if (pista == null) {
                            System.out.println("No se encontró la pista.");
                        } else {
                            System.out.println(pista);
                        }

                        break;
                    }

                    case 10: {
                        System.out.print("Código de la pista: ");
                        String codigo = teclado.nextLine();

                        System.out.print("Nueva descripción: ");
                        String descripcion = teclado.nextLine();

                        System.out.print("Nuevo tipo de evidencia: ");
                        String tipo = teclado.nextLine();

                        System.out.print("Nueva importancia (1-10): ");
                        int importancia = teclado.nextInt();
                        teclado.nextLine();

                        System.out.print("Nueva confiabilidad (0-100): ");
                        int confiabilidad = teclado.nextInt();
                        teclado.nextLine();

                        casoActivo.modificarPista(
                            codigo,
                            descripcion,
                            tipo,
                            importancia,
                            confiabilidad
                        );

                        System.out.println("Pista modificada.");
                        break;
                    }

                    case 11: {
                        System.out.print("Código de la pista que desea eliminar: ");
                        String codigo = teclado.nextLine();

                        casoActivo.eliminarPista(codigo);

                        System.out.println("Pista eliminada.");
                        break;
                    }

                    case 12: {
                        System.out.println(
                            "Ubicaciones registradas: " +
                            casoActivo.getCantidadUbicacionesRegistradas()
                        );

                        System.out.println(
                            "Espacios disponibles: " +
                            casoActivo.getEspaciosDisponibles()
                        );

                        Ubicacion mayorRiesgo =
                            casoActivo.getUbicacionMayorRiesgo();

                        if (mayorRiesgo == null) {
                            System.out.println(
                                "No hay ubicaciones registradas."
                            );
                        } else {
                            System.out.println(
                                "Ubicación con mayor riesgo:"
                            );
                            System.out.println(mayorRiesgo);
                        }

                        System.out.println(
                            "Cantidad de pistas: " +
                            casoActivo.getCantidadPistas()
                        );

                        Pista mayorImportancia =
                            casoActivo.getPistaMayorImportancia();

                        if (mayorImportancia == null) {
                            System.out.println(
                                "No hay pista de mayor importancia."
                            );
                        } else {
                            System.out.println(
                                "Pista con mayor importancia:"
                            );
                            System.out.println(mayorImportancia);
                        }

                        Pista mayorConfiabilidad =
                            casoActivo.getPistaMayorConfiabilidad();

                        if (mayorConfiabilidad == null) {
                            System.out.println(
                                "No hay pista de mayor confiabilidad."
                            );
                        } else {
                            System.out.println(
                                "Pista con mayor confiabilidad:"
                            );
                            System.out.println(mayorConfiabilidad);
                        }

                        System.out.println(
                            "Promedio de importancia: " +
                            casoActivo.getPromedioImportancia()
                        );

                        break;
                    }

                    case 13: {
                        System.out.println("Programa finalizado.");
                        break;
                    }

                    default: {
                        System.out.println(
                            "Opción inválida. Seleccione del 1 al 13."
                        );
                        break;
                    }
                }

            } catch (java.util.InputMismatchException e) {
                System.out.println(
                    "Error: debe ingresar un valor numérico."
                );

                teclado.nextLine();

            } catch (IllegalArgumentException |
                     IllegalStateException |
                     IndexOutOfBoundsException e) {

                System.out.println("Error: " + e.getMessage());

            } finally {
                System.out.println("Operación finalizada.");
            }
        }

        teclado.close();
    }

    public static void mostrarMenu() {
        System.out.println("\n=== MENÚ PRINCIPAL ===");
        System.out.println("1. Nuevo caso");
        System.out.println("2. Registrar ubicación");
        System.out.println("3. Consultar ubicaciones");
        System.out.println("4. Consultar una ubicación");
        System.out.println("5. Modificar ubicación");
        System.out.println("6. Descartar ubicación");
        System.out.println("7. Registrar pista");
        System.out.println("8. Consultar pistas");
        System.out.println("9. Buscar pista");
        System.out.println("10. Modificar pista");
        System.out.println("11. Eliminar pista");
        System.out.println("12. Mostrar reporte de investigación");
        System.out.println("13. Salir");
        System.out.print("Seleccione una opción: ");
    }
}