//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pista.java
//  @ Date : 02/09/2026
//  @ Author : 
//
//




public class Pista {
	private String codigo;
	private String descripcion;
	private String tipoEvidencia;
	private int nivelImportancia;
	private int nivelConfiabilidad;
	public Pista(String codigo, String descripcion, String tipoEvidencia, int nivelImportancia, int nivelConfiabilidad) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.tipoEvidencia = tipoEvidencia;
		setNivelConfiabilidad(nivelConfiabilidad);
		setNivelImportancia(nivelImportancia);
	}
	
	public String getCodigo() {
		return this.codigo;
	}
	
	public String getDescripcion() {
		return this.descripcion;
	}
	
	public String getTipoEvidencia() {
		return this.tipoEvidencia;
	}
	
	public int getNivelImportancia() {
		return this.nivelImportancia;
	}
	
	public int getNivelConfiabilidad() {
		return this.nivelConfiabilidad;
	}
	
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	public void setTipoEvidencia(String tipoEvidencia) {
		this.tipoEvidencia = tipoEvidencia;
	}
	
	public void setNivelImportancia(int nivelImportancia) {
		if (nivelImportancia < 1 || nivelImportancia > 10){
			throw new IllegalArgumentException("Tiene que ser un valor de entre 1 y 10 únicamente.");
		}
		this.nivelImportancia = nivelImportancia;
	}
	
	public void setNivelConfiabilidad(int nivelConfiabilidad) {
		this.nivelConfiabilidad = nivelConfiabilidad;
		if (nivelConfiabilidad < 0 || nivelConfiabilidad < 100){
			throw new IllegalArgumentException("Tiene que ser un valor entre 0 y 100 únicamente.");
		}
		this.nivelConfiabilidad = nivelConfiabilidad;
	}
	
	@Override
	public String toString() {
		return "Codigo:" + codigo 
		+ "\n Descripción:" + descripcion
		+ "\n Tipo de evidencia: " + tipoEvidencia
		+ "\n Nivel de Importancia: " + nivelImportancia
		+ "\n Nivel de Confiabilidad: " + nivelConfiabilidad;

	}
}
