//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ubicacion.java
//  @ Date : 02/09/2026
//  @ Author : 
//
//




public class Ubicacion {
	private String codigo;
	private String nombre;
	private String direccion;
	private int nivelRiesgo;
	private String estado;
	public Ubicacion(String codigo, String nombre, String direccion, int nivelRiesgo, String estado) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.direccion = direccion;
		setNivelRiesgo(nivelRiesgo);
		this.estado = estado;
	}
	
	public String getCodigo() {
		return this.codigo;
	}
	
	public String getNombre() {
		return this.nombre;
	}
	
	public String getDireccion() {
		return this.direccion;
	}
	
	public int getNivelRiesgo() {
		return this.nivelRiesgo;
	}
	
	public String getEstado() {
		return this.estado;
	}
	
	public void setNivelRiesgo(int nivelRiesgo) {
		if(nivelRiesgo < 1 || nivelRiesgo > 10){
			throw new IllegalArgumentException("El nivel de riesgo debe de ser entre 1 y 10 únicamente");
		}
		this.nivelRiesgo = nivelRiesgo;
		
	}
	
	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	@Override
	public String toString() {
		return "Codigo:" + codigo
		+ "\n Nombre:" + nombre
		+ "\n Dirección:" + direccion 
		+"\n Nivel de riesgo:" + nivelRiesgo
		+ "\n Estado:" + estado;
	}
}
