//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : main.java
//  @ Date : 05/08/2026
//  @ Author : 
//
//

import java.util.Scanner;

public class main {
	public static void main(String[] args) {
		Scanner teclado = new Scanner(System.in);
		
		System.out.println("=== Batalla de Pals ===");
		System.out.print("Nombre del Entrenador 1: ");
		String nombre1 = teclado.nextLine();
		System.out.print("Nombre del Entrenador 2: ");
		String nombre2 = teclado.nextLine();
		
		Entrenador entrenador1 = new Entrenador(nombre1);
		Entrenador entrenador2 = new Entrenador(nombre2);
		Batalla batalla = new Batalla(entrenador1, entrenador2);
		
		int ronda = 1;
		while (ronda <= 4) {
			System.out.println("\n----- Ronda " + ronda + " -----");
			
			Pal pal1 = elegirPalUsuario(teclado, entrenador1);
			boolean usarHabilidad1 = preguntarHabilidad(teclado, entrenador1, pal1);
			
			Pal pal2 = elegirPalUsuario(teclado, entrenador2);
			boolean usarHabilidad2 = preguntarHabilidad(teclado, entrenador2, pal2);
			
			Entrenador ganadorRonda = batalla.jugarRonda(pal1, pal2, usarHabilidad1, usarHabilidad2);
			
			if (ganadorRonda == null) {
				System.out.println("¡Ronda empatada!");
			} else {
				System.out.println("¡Gana la ronda " + ganadorRonda.getNombre() + "!");
			}
			
			ronda++;
		}
		
		System.out.println("\n=== Resultado final ===");
		System.out.println(entrenador1.getNombre() + ": " + entrenador1.getRondasGanadas() + " rondas ganadas");
		System.out.println(entrenador2.getNombre() + ": " + entrenador2.getRondasGanadas() + " rondas ganadas");
		
		Entrenador ganadorFinal = batalla.determinarGanador();
		if (ganadorFinal == null) {
			System.out.println("¡La batalla terminó en empate!");
		} else {
			System.out.println("¡El ganador de la batalla es " + ganadorFinal.getNombre() + "!");
		}
		
		teclado.close();
	}
	
	public static Pal elegirPalUsuario(Scanner teclado, Entrenador entrenador) {
		System.out.println(entrenador.getNombre() + ", elige tu Pal:");
		Pal[] equipo = entrenador.getEquipo();
		
		int i = 0;
		while (i < equipo.length) {
			if (equipo[i] != null) {
				System.out.println(i + ". " + equipo[i].getNombre() + " (" + equipo[i].getTipo() + ")");
			}
			i++;
		}
		
		System.out.print("Ingresa el número del Pal: ");
		int indice = Integer.parseInt(teclado.nextLine());
		
		return entrenador.elegirPal(indice);
	}
	
	public static boolean preguntarHabilidad(Scanner teclado, Entrenador entrenador, Pal pal) {
		System.out.print(entrenador.getNombre() + ", ¿usar habilidad especial de " + pal.getNombre() + "? (s/n): ");
		String respuesta = teclado.nextLine();
		return respuesta.equalsIgnoreCase("s");
	}
}