//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteca.java
//  @ Date : 19/08/2026
//  @ Author : 
//
import java.util.ArrayList;


public class Biblioteca {
	private ArrayList<Prestamo> prestamos;
	
	public Biblioteca() {
		prestamos = new ArrayList<Prestamo>();
	}
	
	public boolean registrarPrestamo(int codigoPrestamo,
			String carneEstudiante, String nombreEstudiante,
			String tituloLibro, int diasAutorizados) {
		
		if (existeCodigo(codigoPrestamo)) {
			return false;
		}
		
		if (carneEstudiante == null
				|| carneEstudiante.isEmpty()) {
			
			return false;
		}
		
		if (nombreEstudiante == null
				|| nombreEstudiante.isEmpty()) {
			
			return false;
		}
		
		if (tituloLibro == null
				|| tituloLibro.isEmpty()) {
			
			return false;
		}
		
		if (diasAutorizados <= 0) {
			return false;
		}
		
		Prestamo nuevoPrestamo = new Prestamo(
				codigoPrestamo,
				carneEstudiante,
				nombreEstudiante,
				tituloLibro,
				diasAutorizados);
		
		prestamos.add(nuevoPrestamo);
		
		return true;
	}
	
	public ArrayList<Prestamo> consultarPrestamos() {
		return prestamos;
	}
	
	public Prestamo buscarPrestamo(int codigoPrestamo) {
		int posicion = -1;
		
		for (int i = 0; i < prestamos.size(); i++) {
			if (prestamos.get(i).getCodigoPrestamo()
					== codigoPrestamo) {
				
				posicion = i;
			}
		}
		
		return prestamos.get(posicion);
	}
	
	public boolean modificarPrestamo(int codigoPrestamo,
			String nuevoTitulo, int nuevosDias) {
		
		if (nuevoTitulo == null
				|| nuevoTitulo.isEmpty()) {
			
			return false;
		}
		
		if (nuevosDias <= 0) {
			return false;
		}
		
		Prestamo prestamo =
				buscarPrestamo(codigoPrestamo);
		
		prestamo.setTitulolibro(nuevoTitulo);
		prestamo.setDiasAutorizados(nuevosDias);
		
		return true;
	}
	
	public boolean registrarDevolucion(int codigoPrestamo) {
		int posicion = -1;
		
		for (int i = 0; i < prestamos.size(); i++) {
			if (prestamos.get(i).getCodigoPrestamo()
					== codigoPrestamo) {
				
				posicion = i;
			}
		}
		
		prestamos.remove(posicion);
		
		return true;
	}
	
	public ArrayList<Prestamo> consultarPorEstudiante(
			String carneEstudiante) {
		
		ArrayList<Prestamo> prestamosEstudiante =
				new ArrayList<Prestamo>();
		
		for (Prestamo prestamo : prestamos) {
			if (prestamo.getCarneEstudiante()
					.equalsIgnoreCase(carneEstudiante)) {
				
				prestamosEstudiante.add(prestamo);
			}
		}
		
		return prestamosEstudiante;
	}
	
	public int calcularTotalDiasAutorizados() {
		int totalDias = 0;
		
		for (Prestamo prestamo : prestamos) {
			totalDias += prestamo.getDiasAutorizados();
		}
		
		return totalDias;
	}
	
	public Prestamo obtenerPrestamoMayorDuracion() {
		Prestamo prestamoMayor = prestamos.get(0);
		
		for (Prestamo prestamo : prestamos) {
			if (prestamo.getDiasAutorizados()
					> prestamoMayor.getDiasAutorizados()) {
				
				prestamoMayor = prestamo;
			}
		}
		
		return prestamoMayor;
	}
	
	public int obtenerCantidadPrestamos() {
		return prestamos.size();
	}
	
	private boolean existeCodigo(int codigoPrestamo) {
		for (Prestamo prestamo : prestamos) {
			if (prestamo.getCodigoPrestamo()
					== codigoPrestamo) {
				
				return true;
			}
		}
		
		return false;
	}
}
