//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : main.java
//  @ Date : 19/08/2026
//  @ Author : 
//
//



import java.util.ArrayList;
import java.util.Scanner;

public class main {
	private static Scanner scanner = new Scanner(System.in);
	private static Biblioteca biblioteca = new Biblioteca();
	
	public static void main(String[] args) {
		mostrarMenu();
		scanner.close();
	}
	
	public static void mostrarMenu() {
		int opcion = 0;
		
		while (opcion != 10) {
			System.out.println("\n==============================");
			System.out.println("   BIBLIOTECA UNIVERSITARIA");
			System.out.println("==============================");
			System.out.println("1. Registrar préstamo");
			System.out.println("2. Consultar préstamos");
			System.out.println("3. Buscar préstamo");
			System.out.println("4. Modificar préstamo");
			System.out.println("5. Registrar devolución");
			System.out.println("6. Consultar por estudiante");
			System.out.println("7. Reporte de días autorizados");
			System.out.println("8. Préstamo con mayor duración");
			System.out.println("9. Cantidad de préstamos");
			System.out.println("10. Salir");
			System.out.println("==============================");
			System.out.print("Seleccione una opción: ");
			
			try {
				opcion = scanner.nextInt();
				scanner.nextLine();
				
				switch (opcion) {
					case 1:
						opcionRegistrarPrestamo();
						break;
						
					case 2:
						opcionConsultarPrestamos();
						break;
						
					case 3:
						opcionBuscarPrestamo();
						break;
						
					case 4:
						opcionModificarPrestamo();
						break;
						
					case 5:
						opcionRegistrarDevolucion();
						break;
						
					case 6:
						opcionConsultarPorEstudiante();
						break;
						
					case 7:
						opcionReporteDiasAutorizados();
						break;
						
					case 8:
						opcionPrestamoMayorDuracion();
						break;
						
					case 9:
						opcionCantidadPrestamos();
						break;
						
					case 10:
						System.out.println(
								"Gracias por utilizar el sistema.");
						break;
						
					default:
						System.out.println(
								"Seleccione una opción del 1 al 10.");
						break;
				}
				
			} catch (Exception e) {
				System.out.println(
						"Error: debe ingresar un número.");
				scanner.nextLine();
			}
		}
	}
	
	public static void opcionRegistrarPrestamo() {
		try {
			System.out.println("\n--- REGISTRAR PRÉSTAMO ---");
			
			System.out.print("Código del préstamo: ");
			int codigoPrestamo = scanner.nextInt();
			scanner.nextLine();
			
			System.out.print("Carné del estudiante: ");
			String carneEstudiante = scanner.nextLine();
			
			System.out.print("Nombre del estudiante: ");
			String nombreEstudiante = scanner.nextLine();
			
			System.out.print("Título del libro: ");
			String tituloLibro = scanner.nextLine();
			
			System.out.print("Cantidad de días autorizados: ");
			int diasAutorizados = scanner.nextInt();
			scanner.nextLine();
			
			boolean registrado = biblioteca.registrarPrestamo(
					codigoPrestamo,
					carneEstudiante,
					nombreEstudiante,
					tituloLibro,
					diasAutorizados);
			
			if (registrado) {
				System.out.println(
						"Préstamo registrado correctamente.");
			} else {
				System.out.println(
						"No se pudo registrar el préstamo.");
				System.out.println(
						"Revise los datos ingresados.");
			}
			
		} catch (Exception e) {
			System.out.println(
					"Error: el código y los días deben ser números.");
			scanner.nextLine();
		}
	}
	
	public static void opcionConsultarPrestamos() {
		System.out.println("\n--- PRÉSTAMOS REGISTRADOS ---");
		
		ArrayList<Prestamo> prestamos =
				biblioteca.consultarPrestamos();
		
		if (prestamos.isEmpty()) {
			System.out.println(
					"No existen préstamos registrados.");
		} else {
			for (Prestamo prestamo : prestamos) {
				System.out.println(prestamo);
				System.out.println("------------------------------");
			}
		}
	}
	
	public static void opcionBuscarPrestamo() {
		try {
			System.out.println("\n--- BUSCAR PRÉSTAMO ---");
			
			System.out.print("Código del préstamo: ");
			int codigoPrestamo = scanner.nextInt();
			scanner.nextLine();
			
			Prestamo prestamo =
					biblioteca.buscarPrestamo(codigoPrestamo);
			
			System.out.println("\nPréstamo encontrado:");
			System.out.println(prestamo);
			
		} catch (IndexOutOfBoundsException e) {
			System.out.println(
					"Error: el préstamo no está registrado.");
			
		} catch (Exception e) {
			System.out.println(
					"Error: debe ingresar un código numérico.");
			scanner.nextLine();
		}
	}
	
	public static void opcionModificarPrestamo() {
		try {
			System.out.println("\n--- MODIFICAR PRÉSTAMO ---");
			
			System.out.print("Código del préstamo: ");
			int codigoPrestamo = scanner.nextInt();
			scanner.nextLine();
			
			System.out.print("Nuevo título del libro: ");
			String nuevoTitulo = scanner.nextLine();
			
			System.out.print("Nueva cantidad de días: ");
			int nuevosDias = scanner.nextInt();
			scanner.nextLine();
			
			boolean modificado = biblioteca.modificarPrestamo(
					codigoPrestamo,
					nuevoTitulo,
					nuevosDias);
			
			if (modificado) {
				System.out.println(
						"Préstamo modificado correctamente.");
			} else {
				System.out.println(
						"No se pudo modificar el préstamo.");
			}
			
		} catch (IndexOutOfBoundsException e) {
			System.out.println(
					"Error: el préstamo no está registrado.");
			
		} catch (Exception e) {
			System.out.println(
					"Error: el código y los días deben ser números.");
			scanner.nextLine();
		}
	}
	
	public static void opcionRegistrarDevolucion() {
		try {
			System.out.println("\n--- REGISTRAR DEVOLUCIÓN ---");
			
			System.out.print("Código del préstamo: ");
			int codigoPrestamo = scanner.nextInt();
			scanner.nextLine();
			
			boolean eliminado =
					biblioteca.registrarDevolucion(codigoPrestamo);
			
			if (eliminado) {
				System.out.println(
						"Devolución registrada correctamente.");
			}
			
		} catch (IndexOutOfBoundsException e) {
			System.out.println(
					"Error: el préstamo no está registrado.");
			
		} catch (Exception e) {
			System.out.println(
					"Error: debe ingresar un código numérico.");
			scanner.nextLine();
			
		} finally {
			System.out.println(
					"Proceso de devolución terminado.");
		}
	}
	
	public static void opcionConsultarPorEstudiante() {
		try {
			System.out.println(
					"\n--- CONSULTAR POR ESTUDIANTE ---");
			
			System.out.print("Carné del estudiante: ");
			String carneEstudiante = scanner.nextLine();
			
			ArrayList<Prestamo> prestamosEstudiante =
					biblioteca.consultarPorEstudiante(
							carneEstudiante);
			
			if (prestamosEstudiante.isEmpty()) {
				System.out.println(
						"El estudiante no tiene préstamos.");
			} else {
				for (Prestamo prestamo : prestamosEstudiante) {
					System.out.println(prestamo);
					System.out.println(
							"------------------------------");
				}
			}
			
		} catch (NullPointerException e) {
			System.out.println(
					"Error al consultar los préstamos.");
		}
	}
	
	public static void opcionReporteDiasAutorizados() {
		System.out.println(
				"\n--- REPORTE DE DÍAS AUTORIZADOS ---");
		
		int totalDias =
				biblioteca.calcularTotalDiasAutorizados();
		
		System.out.println(
				"Total de días autorizados: " + totalDias);
	}
	
	public static void opcionPrestamoMayorDuracion() {
		try {
			System.out.println(
					"\n--- PRÉSTAMO CON MAYOR DURACIÓN ---");
			
			Prestamo prestamoMayor =
					biblioteca.obtenerPrestamoMayorDuracion();
			
			System.out.println(prestamoMayor);
			
		} catch (IndexOutOfBoundsException e) {
			System.out.println(
					"Error: no existen préstamos registrados.");
		}
	}
	
	public static void opcionCantidadPrestamos() {
		System.out.println(
				"\n--- CANTIDAD DE PRÉSTAMOS ---");
		
		int cantidad =
				biblioteca.obtenerCantidadPrestamos();
		
		System.out.println(
				"Préstamos registrados: " + cantidad);
	}
}