//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Prestamo.java
//  @ Date : 19/08/2026
//  @ Author : 
//
//




public class Prestamo {
	private int codigoPrestamo;
	private String carneEstudiante;
	private String tituloLibro;
	private String nombreEstudiante;
	private int diasAutorizados;


	public Prestamo(int codigoPrestamo, String carneEstudiante, String nombreEstudiante, String tituloLibro, int diasAutorizados) {
		this.codigoPrestamo = codigoPrestamo;
		this.carneEstudiante = carneEstudiante;
		this.nombreEstudiante = nombreEstudiante;
		this.tituloLibro = tituloLibro;
		this.diasAutorizados = diasAutorizados;
	}
	
	public int getCodigoPrestamo() {
		return codigoPrestamo;
	}
	
	public String getCarneEstudiante() {
		return carneEstudiante;
	}
	
	public String getNombreEstudiante() {
		return nombreEstudiante;
	}
	
	public String getTituloLibro() {
		return tituloLibro;
	}
	
	public void setTitulolibro(String tituloLibro) {
		this.tituloLibro = tituloLibro;
	}
	
	public int getDiasAutorizados() {
		return diasAutorizados;
	}
	
	public void setDiasAutorizados(int diasAutorizados) {
		this.diasAutorizados = diasAutorizados;
	}
	
	public String toString() {
		return "Codigo del prestamo:" + codigoPrestamo + "\n Carné del estudiante: " + carneEstudiante + "\nNombre del estudiante: " + nombreEstudiante + 
		"\nTitulo del libro: " + tituloLibro + "\nDias autorizados: " + diasAutorizados;
	}
}
