//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FuenteChocolate.java
//  @ Date : 23/09/2026
//  @ Author : 
//
//




public class FuenteChocolate extends Maquina {
	public double capacidadKg;
	public FuenteChocolate(String codigoInventario, String marca, String modelo, double tarifaDiaria, double capacidadKg) {
		this.codigoInventario = codigoInventario;
		this.marca = marca;
		this.modelo = modelo;
		this.tarifaDiaria = tarifaDiaria;
		this.capacidadKg = capacidadKg;
		if (capacidadKg <= 0 ){
			throw new IllegalArgumentException("No puede ser menor que 0");
		}
		if (tarifaDiaria <= 0){
			throw new IllegalStateException("No puede ser menor que 0");
		}
		if (codigoInventario == null||codigoInventario.trim().isEmpty()){
			throw new IllegalArgumentException("El código no debe estar vacío");
		}
	}
	
	public double getCapacidadKg() {
		return this.capacidadKg;
	}
	
	@Override
	
	public double calcularCosto(int dias) {
		if (dias >= 0 ){
			throw new IllegalStateException("Los dias no pueden ser menores a 0");
		}
		return this.capacidadKg + 20 * dias;
	}
	
	public String obtenerDetalles() {
		String detalles = "-- Fuente de Chocolate--";
		detalles += "\n Capacidad en KG:" + this.capacidadKg;
		return detalles;
	}
	
	public String getCategoria() {
		return "Chocolate";
	}


}
