//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Maquina.java
//  @ Date : 23/09/2026
//  @ Author : 
//
//




public abstract class Maquina {
	protected String codigoInventario;
	protected String marca;
	protected String modelo;
	protected double tarifaDiaria;
	protected boolean disponible = true;
	
	public String getCodigoInventario() {
		return  codigoInventario;
	}
	
	public String getMarca() {
		return marca;

	}
	
	public String getModelo() {
		return modelo;
	}
	
	public double getTarifaDiaria() {
		return  tarifaDiaria;
	}
	
	public boolean isDisponibilidad() {
		return disponible;
	}
	
	public void alquilar() {
		if (!this.disponible){	throw new IllegalStateException("La maquina no esta disponible");
	}
		this.disponible = false;
	}
	
	public void devolver() {
		if (this.disponible){
			throw new IllegalStateException("La maquina fue devuelta");
		}
		this.disponible = true;
	}
	
	public abstract double calcularCosto(int dias);
		
	
	public abstract String obtenerDetalles();
	
	public abstract String getCategoria();
}
