//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaquinaAlgodon.java
//  @ Date : 23/09/2026
//  @ Author : 
//
//




public class MaquinaAlgodon extends Maquina {
	private int potenciaVattios;
	public MaquinaAlgodon(String codigoInventario, String marca, String modelo, double tarifaDiaria, int potenciaVattios) {
		this.codigoInventario = codigoInventario;
		this.marca = marca;
		this.modelo = modelo;
		this.tarifaDiaria = tarifaDiaria;
		this.potenciaVattios = potenciaVattios;
		if (tarifaDiaria <= 0){
			throw new IllegalStateException("No puede ser menor que 0");
		}
		if (potenciaVattios < 400){
			throw new IllegalStateException("No puede ser menor que 1000 W");
		}
		if (codigoInventario == null||codigoInventario.trim().isEmpty()){
			throw new IllegalArgumentException("El código no debe estar vacío");
		}
	}
	
	public int getPotenciaVatios() {
		return this.potenciaVattios;
	}
	
@Override 
	
	public double calcularCosto(int dias) { 
		if (dias >= 0){
			throw new IllegalArgumentException("Los dias no pueden ser menores a 0"); }
		if (this.potenciaVattios > 1000){
			return (super.tarifaDiaria + 25) * dias;
		}
		return this.tarifaDiaria * dias + 60;
	}
	
	public String obtenerDetalles() {
	 System.out.println("--Algodon de Azucar--");
		return "Capacidad Máxima Vatttios" + this.potenciaVattios + "W";

	}
	public String getCategoria() {
		return "Algodon";
	}
}
