//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaquinaPalomitas.java
//  @ Date : 23/09/2026
//  @ Author : 
//
//




public class MaquinaPalomitas extends Maquina {
	private int porcionesPorHora;
	private boolean carritoIntegrado;
	public MaquinaPalomitas(String codigoInventario, String marca, String modelo, double tarifaDiaria, int porcionesPorHora, boolean carritoIntegrado) {
		this.codigoInventario = codigoInventario;
		this.marca = marca;
		this.modelo = modelo;
		this.tarifaDiaria = tarifaDiaria;
		this.porcionesPorHora = porcionesPorHora;
		this.carritoIntegrado = carritoIntegrado;
		if (porcionesPorHora <= 0 ){
			throw new IllegalArgumentException("No puede ser menor que 0");
		}
		if (codigoInventario == null||codigoInventario.trim().isEmpty()){
			throw new IllegalArgumentException("El código no debe estar vacío");
		}
	}
	
	public int getPorcionesPorHora() {
		return this.porcionesPorHora;
	}
	
	public boolean tieneCarritoIntegrado() {
		return this.carritoIntegrado;
	}
	
	@Override
	
	
	public double calcularCosto(int dias) {
		if (dias >= 0){
			throw new IllegalArgumentException("Los dias no pueden ser menores a 0");
		}
		if (carritoIntegrado){
			return (tarifaDiaria + 40) * dias;
		}
		return this.tarifaDiaria + 40;
	}
	
	public String obtenerDetalles() {
    String detalles = "-- Máquina Palomitas --";
    detalles += "\nPorciones por hora: " + this.porcionesPorHora;

    if (this.carritoIntegrado) {
        detalles += "\nCarrito integrado";
    } else {
        detalles += "\nCarrito no integrado";
    }

    return detalles;
}
	
	public String getCategoria() {
		return "Palomitas";
	}	

}
